CREATE TABLE users(
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fullname VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    picture VARCHAR(255) NOT NULL DEFAULT "",
    password VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL DEFAULT "",
    currency VARCHAR(255) NOT NULL DEFAULT "",
    joined_on DATETIME NOT NULL DEFAULT CURRENT_TIME
)